# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - petandcareAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set executable permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar  # Cambiado a bootJar para construir el JAR

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
            name: java-app
            path: './build/libs/*.jar'  # Ajusta la ruta para buscar el JAR

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB5A72458DCB4E938AD2C3D2A745050F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_83B656C94C47431B82EA781FFE754BEF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5045142E81914E93A424DFC489333B7B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'petandcareAPI'
          slot-name: 'Production'
          package: '*.jar'
          